import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.navy },
  scroll: { flexGrow: 1 },
  top: { alignItems: 'center', paddingTop: 72, paddingBottom: 32 },
  logoContainer: { width: 56, height: 56, borderRadius: 16, backgroundColor: COLORS.gold, justifyContent: 'center', alignItems: 'center', marginBottom: 14 },
  logoIcon: { fontSize: 24, color: COLORS.white },
  logo: { fontSize: 28, fontWeight: 'bold', color: COLORS.white, letterSpacing: 4 },
  tagline: { fontSize: 13, color: COLORS.gray400, marginTop: 6, letterSpacing: 0.5 },
  form: { backgroundColor: COLORS.white, borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 28, paddingBottom: 48, flex: 1 },
  formTitle: { fontSize: 24, fontWeight: 'bold', color: COLORS.navy, marginBottom: 4 },
  formSubtitle: { fontSize: 14, color: COLORS.gray500, marginBottom: 24 },
  fieldGroup: { marginBottom: 16 },
  label: { fontSize: 13, fontWeight: '600', color: COLORS.gray700, marginBottom: 7 },
  inputWrap: { flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderColor: COLORS.gray200, borderRadius: 12, backgroundColor: COLORS.gray100, paddingHorizontal: 12 },
  inputError: { borderColor: COLORS.red },
  inputIcon: { marginRight: 8 },
  input: { flex: 1, paddingVertical: 13, fontSize: 14, color: COLORS.gray900 },
  eyeBtn: { padding: 4 },
  errorText: { fontSize: 12, color: COLORS.red, marginTop: 5, marginLeft: 2 },
  hint: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.goldLight, borderRadius: 8, padding: 10, marginBottom: 20 },
  hintText: { fontSize: 12, color: COLORS.goldDark },
  button: { backgroundColor: COLORS.gold, padding: 15, borderRadius: 12, alignItems: 'center', marginBottom: 16, elevation: 2 },
  buttonDisabled: { opacity: 0.7 },
  buttonText: { color: COLORS.white, fontWeight: 'bold', fontSize: 16, letterSpacing: 0.5 },
  dividerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  dividerLine: { flex: 1, height: 1, backgroundColor: COLORS.gray200 },
  dividerText: { fontSize: 13, color: COLORS.gray400, marginHorizontal: 12 },
  outlineButton: { borderWidth: 1.5, borderColor: COLORS.navy, padding: 14, borderRadius: 12, alignItems: 'center' },
  outlineButtonText: { color: COLORS.navy, fontWeight: 'bold', fontSize: 15 },
});